### ISSUE TITLE
[Bug]: Opening PR from GH Action run on PR check results in error state

### ISSUE THREAD

**Issue by axelcedercreutz** [replexica/replexica#334]
### What
My goal is to add any missing translations in a PR by opening a separate PR for the added translations. I've implemented it based on the [documented instructions](https://docs.replexica.com/setup/gha) but I'm running into the following type of error:

```
Run replexica/replexica@main
/usr/bin/docker run --name dc3cbf7f45dbf856c4306b[9](https://github.com/{ORG_NAME}/{REPO_NAME}/actions/runs/12084148795/job/33698707115?pr=296#step:4:10)2b775c5fbf3c4e_d0b717 --label 0dc3cb --workdir /github/workspace --rm -e "GH_TOKEN" -e "INPUT_API-KEY" -e "INPUT_PULL-REQUEST" -e "INPUT_PULL-REQUEST-TITLE" -e "INPUT_COMMIT-MESSAGE" -e "REPLEXICA_API_KEY" -e "REPLEXICA_PULL_REQUEST" -e "REPLEXICA_COMMIT_MESSAGE" -e "REPLEXICA_PULL_REQUEST_TITLE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/{REPO_NAME}/{REPO_NAME}":"/github/workspace" 0dc3cb:f7f45dbf856c4306b92b775c5fbf3c4e
ℹ Pull request mode: on
- Configuring git
✔ Git configured
- Calculating automated branch name
✔ Automated branch name calculated: replexica/296/merge
- Checking if branch exists
✔ Branch does not exist
- Creating branch replexica/296/merge
fatal: couldn't find remote ref 296/merge
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: git fetch origin 296/merge
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at PullRequestFlow.createI18nBranch (file:///app/build/flows/pull-request.js:[10](https://github.com/{ORG_NAME}/{REPO_NAME}/actions/runs/12084148795/job/33698707115?pr=296#step:4:11)0:9)
    at PullRequestFlow.preRun (file:///app/build/flows/pull-request.js:23:18)
    at async main (file:///app/build/index.js:14:5) {
  status: [12](https://github.com/{ORG_NAME}/{REPO_NAME}/actions/runs/12084148795/job/33698707115?pr=296#step:4:13)8,
  signal: null,
  output: [ null, null, null ],
  pid: 20,
  stdout: null,
  stderr: null
}

Node.js v20.12.2
```

The GH Action looks like following:

```
name: Localization

on:
  pull_request:
    branches-ignore:
      - "dependabot-**"

jobs:
  localize:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Replexica Localization
        uses: replexica/replexica@main
        with:
          api-key: ${{ secrets.REPLEXICA_API_KEY }}
          pull-request: true
        env:
          GH_TOKEN: ${{ github.token }}
```

### Why
Being able to open PRs that are related to a PR would improve the DX, as it would allow us to automate the translations already when the PRs are being merged to staging.

### How
I guess being able to somehow specify the branch better since the auto detection doesn't seem to work properly?
